/**
 * 错误码权威登记册（设计约束#3 fail-closed 闸配套·镜像旧线 shared/errors.ts——码是前端分支契约，
 * 不可改名、新增只追加）。并存期 parity 测试焊死与旧线逐键一致；新线 kit err() 随 M1 kit 批接上本册。
 */
export const ERR = {
  // 闸 / 身份
  NO_OPENID: 'NO_OPENID',
  ADMIN_ONLY: 'ADMIN_ONLY',
  SERVER_ONLY: 'SERVER_ONLY',
  // 通用参数 / 校验
  NO_ID: 'NO_ID',
  NO_TYPE: 'NO_TYPE',
  BAD_ARGS: 'BAD_ARGS',
  BAD_QTY: 'BAD_QTY',
  BAD_ADDRESS: 'BAD_ADDRESS',
  EMPTY_ITEMS: 'EMPTY_ITEMS',
  EMPTY_PATCH: 'EMPTY_PATCH',
  META_TOO_BIG: 'META_TOO_BIG',
  TOO_MANY_ITEMS: 'TOO_MANY_ITEMS',
  NOT_FOUND: 'NOT_FOUND',
  // 订单 / 支付
  BAD_STATUS: 'BAD_STATUS',
  NO_PRODUCT: 'NO_PRODUCT',
  NO_MAIN_ITEM: 'NO_MAIN_ITEM',
  ORDER_ID_BUSY: 'ORDER_ID_BUSY',
  ORDER_CLOSED: 'ORDER_CLOSED',
  PAY_NOT_ENABLED: 'PAY_NOT_ENABLED',
  PAY_CONFIG_MISSING: 'PAY_CONFIG_MISSING',
  UNIFIED_ORDER_FAIL: 'UNIFIED_ORDER_FAIL',
  // 售后 / 退款
  ALREADY_APPLIED: 'ALREADY_APPLIED',
  NOT_REFUNDABLE: 'NOT_REFUNDABLE',
  NOT_IN_ORDER: 'NOT_IN_ORDER',
  // 激活 / 课程
  INVALID_CODE: 'INVALID_CODE',
  CODE_TAKEN: 'CODE_TAKEN',
  NOTHING_LEFT: 'NOTHING_LEFT',
  NOT_ACTIVATED: 'NOT_ACTIVATED',
  NOT_ENTITLED: 'NOT_ENTITLED',
  NOT_DONE: 'NOT_DONE',
  NO_COURSE: 'NO_COURSE',
  NO_SEGMENT: 'NO_SEGMENT',
  // 评价
  BAD_RATING: 'BAD_RATING',
  REVIEWED: 'REVIEWED',
  // 频控
  RATE_LIMITED: 'RATE_LIMITED',
  // 客服 / 身份桥接
  NO_UNIONID: 'NO_UNIONID',
  KF_NOT_CONFIGURED: 'KF_NOT_CONFIGURED',
  TOKEN_FAILED: 'TOKEN_FAILED',
  NO_EXTERNAL_USERID: 'NO_EXTERNAL_USERID',
  // 反馈 / 内容安全
  EMPTY_FEEDBACK: 'EMPTY_FEEDBACK',
  IMG_RISKY: 'IMG_RISKY',
  SEC_CHECK_FAIL: 'SEC_CHECK_FAIL',
} as const

export type ErrCode = (typeof ERR)[keyof typeof ERR]
